Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 11000, host: 11000

  config.vm.provider "virtualbox" do |vb|
		vb.name = "dataiku"
		vb.memory = 5024
  		vb.cpus = 2
   end
   
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
	
  end
  
end
